#$ -S /bin/bash
#$ -j y
#$ -l tmem=12G
#$ -l gpu=true
##$ -l gpu_titanxp=1
##$ -l gpu_p100=1
#$ -l h_rt=10:00:00
#$ -wd /home/daniravi/dani_net
#$ -t 40-142
#$ -tc 50
#$ -pe gpu 1


hostname
date

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-9.0.source


python3 main.py --savedir /SAN/medic/Alz_prog/save --conf 3 --slice $SGE_TASK_ID

date
